- id: flakehell
  name: flakehell
  description: "Flakehell: Flake8 wrapper to make it nice, legacy-friendly, configurable"
  entry: "python flakehell/__main__.py lint ."
  language: python
  language_version: python3
  require_serial: true
  types: [python]